### ISSUE TITLE
kubectl: Unable to connect to the server: x509 error

### ISSUE THREAD

**Issue by vielmetti** [zeerorg/k3s-in-docker#3]
```
ed@Eds-MacBook-Pro ~ (master) $ kubectl get pods --all-namespaces
Unable to connect to the server: x509: certificate is valid for docker-for-desktop, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, host.docker.internal, not localhost
```

**Comment by vielmetti** [comment]
Looks like I ran into this:

https://linuxacademy.com/community/posts/show/topic/31095-kubectl-remote-access-beware-docker-for-desktop-on-macos

**Comment by vielmetti** [comment]
To solve (and this is for the Mac), go into Docker Desktop, select the Kubernetes menu, "disable Kubernetes". Then `kubectl` points to the correct server.

**Comment by zeerorg** [comment]
Thanks for using it on mac 😄 

I thought that doing `k3d create` when the port was in use should give an error from docker and the cluster won't be created. This issue could be documented.
